export { Svg3D } from './Svg3D';
export { LayeredSvg3D } from './LayeredSvg3D';
export type { LayeredSvg3DProps } from './LayeredSvg3D';
export { PRESETS } from './presets';
export { canvasToPngBlob, downloadBlob, exportCanvasPng, exportSceneGlb, sanitizeSvg, readSvgFile } from './export';
export { analyzeSvg, applyOverrides, buildLayerSvgs, layerTransforms, estimateVertices, estimateTriangles, topLevelGroups, extractShapes, pickGranularity, resolveFillColor, VERTEX_BUDGET, TRIANGLE_BUDGET } from './intelligence';
export { analyzeSvgAsync, disposeAnalysisWorker } from './analysisWorker';
export type { AssetProfile, SvgLayer, LayerRole, RawGroup, Granularity } from './intelligence';
export { hashSvg, analyzeSvgCached, clearAnalysisCache } from './hash';
export { shapeBBox, pathBBox, overlaps, contains, assignLevels } from './spatial';
export type { BBox } from './spatial';
export { extractGradient } from './gradients';
export type { GradientSpec, GradientStop } from './gradients';
export { makeGradientTextures } from './gradientTextures';
export type { GradientTextures } from './gradientTextures';
export { geometryCache, geoKey, createRefCache } from './geometryCache';
export type { RefCache } from './geometryCache';
export { SCENE_PRESETS } from './scenes';
export type { SceneName, ScenePreset } from './scenes';
export type { Svg3DProps, SVG3DProps, MaterialPreset, PresetName } from './types';
